name: Link Check

on:
  push:
    paths:
      - '**/*.md'
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: lycheeverse/lychee-action@v1
        with:
          args: >
            --no-progress
            --exclude 'https://github.com/nattapongsindhu'
            './**/*.md'
          fail: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
